apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx  # Matches the labels in the Deployment
  ports:
    - protocol: TCP
      port: 80         # The port the service will expose
      targetPort: 80   # The port the container listens on
  type: ClusterIP

